dictionaries = ["en_gb"]
words = [
    "Ansible's",
    "Cachy",
    "DSL's",
    "Kubernetes",
    "Kyokushin",
    "Nakama",
    "Québec",
    "Shinkyokushin",
    "Shodan",
    "Thinkbook",
    "Zettelkasten",
    "acpi",
    "analyzer",
    "ansible",
    "ansiblels",
    "antosha",
    "apic",
    "asmfmt",
    "augroup",
    "autoindent",
    "autopairs",
    "autoread",
    "autosession",
    "autotag",
    "avrtl",
    "bashls",
    "bibtex",
    "bootloaders",
    "bufnr",
    "cdrom",
    "chown",
    "cmake",
    "cmakelint",
    "codelldb",
    "colemak",
    "colemak's",
    "colorcolumn",
    "commentstring",
    "completeopt",
    "cssls",
    "ctermbg",
    "cursorcolumn",
    "cursorline",
    "customize",
    "cwd",
    "dap",
    "decremental",
    "desai",
    "dockerls",
    "efi",
    "emptor",
    "esszed",
    "evdev",
    "expandtab",
    "fileencoding",
    "fileformat",
    "folke",
    "fzf",
    "ghci",
    "ghcups",
    "gitcommit",
    "gitsigns",
    "glepnir",
    "glyphs",
    "gmc",
    "gmcqc",
    "gomod",
    "gopls",
    "gosum",
    "guibg",
    "guillemet",
    "hls",
    "hlsearch",
    "hoogle",
    "hrsh",
    "hyperv",
    "hypr",
    "hyprctl",
    "hyprland",
    "ignorecase",
    "incsearch",
    "integrations",
    "isort",
    "jglasovic",
    "josean",
    "jsonlint",
    "jsonls",
    "jsregexp",
    "karateka",
    "kdheepak",
    "keybinds",
    "keymap",
    "keymaps",
    "kvm",
    "kyu",
    "linters",
    "liststyle",
    "localectl",
    "lspconfig",
    "lspkind",
    "luadoc",
    "lualine",
    "luasnip",
    "lukas",
    "madhu",
    "makefiles",
    "mapleader",
    "markdownlint",
    "maximizer",
    "maxwidth",
    "menuone",
    "mfussenegger",
    "mkdir",
    "monokai",
    "moonlander",
    "nearline",
    "neovim",
    "netrw",
    "nginx",
    "nixd",
    "nixfmt",
    "nixos",
    "nixpkgs",
    "nmcli",
    "noatime",
    "noremap",
    "noselect",
    "nvim",
    "nvimdev",
    "oldfiles",
    "openssl",
    "oryx",
    "parsers",
    "pci",
    "pydocstyle",
    "pyproject",
    "pyright",
    "qwerty's",
    "reineke",
    "rstcheck",
    "rtc",
    "scrolloff",
    "sdb",
    "sdc",
    "sed",
    "sharkdp",
    "shiftwidth",
    "signcolumn",
    "smartcase",
    "softtabstop",
    "splitbelow",
    "splitright",
    "starship",
    "stevearc",
    "stylelua",
    "stylua",
    "systemdlint",
    "tabclose",
    "tabn",
    "tabnew",
    "tabp",
    "tabstop",
    "tarmak",
    "tem",
    "termguicolors",
    "terraformls",
    "timeoutlen",
    "tlsv",
    "tmux",
    "tpm",
    "tsă",
    "uefi",
    "unnamedplus",
    "vcpu",
    "vda",
    "venv",
    "vimdoc",
    "virt",
    "virtio",
    "vscode",
    "watefall",
    "waybar",
    "wayland",
    "writeback",
    "xdg",
    "xkb",
    "yamlfmt",
    "yamllint",
    "yamlls",
    "zsa",
    "ẞ",
]
ignore_paths = ["nixos/README.md"]
ignore_patterns = ['\b[A-Z]{2,}\b']
