---
formatter:
  type: basic
  force_quote_style: "double"
  include_document_start: true
  indent: 2
  max_line_length: 99
  pad_line_comments: 2
  retain_line_breaks_single: true
  trim_trailing_whitespace: true
